In [1]:
import pandas as pd

In [2]:
df_degradation = pd.read_csv("degradation_results.csv")
df_explanation = pd.read_csv("explanation_results.csv")

In [3]:
df_degradation.head()

   iteration  n_features  train_loss  val_loss  test_loss  n_epochs
0          1        1057    0.005936  0.008069   0.008201        44
1          2         951    0.008042  0.005566   0.005563        32
2          3         855    0.007786  0.010940   0.011110        28
3          4         769    0.004464  0.005535   0.005686        66
4          5         692    0.007616  0.009753   0.009837        27

In [4]:
df_explanation.head()

,iteration,n_features,features_selected,original_indices,test_loss,shap_explanation,positive_fidelity,negative_fidelity
0,1,951,"['nAcid', 'nBase', 'SpAbs_A', 'SpMax_A', 'SpDi...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.008201,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",11.462289,1.373890
1,2,855,"['nAcid', 'nBase', 'SpAbs_A', 'SpMax_A', 'SpDi...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.005563,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",24.885717,1.182231
2,3,769,"['nAcid', 'nBase', 'SpAbs_A', 'SpMax_A', 'SpDi...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.011110,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",16.829027,0.984434
3,4,692,"['nAcid', 'nBase', 'SpAbs_A', 'SpMax_A', 'SpDi...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.005686,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",20.830071,1.272168
4,5,622,"['nAcid', 'nBase', 'SpAbs_A', 'SpMax_A', 'SpDi...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.009837,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",31.157011,1.718943